### ISSUE TITLE
Distribute as AUR package

### ISSUE THREAD

**Issue by vestingz** [cfv-project/cfv#42]
Thanks for Python3 support! Quickly made an AUR package here: https://aur.archlinux.org/packages/cfv-git

**Comment by lxp** [comment]
Thank you!
If you plan to keep the AUR package up-to-date, you can also provide us some install instructions for inclusion in the README.md.
I thought about something like this:

~~~markdown
### From OS-specific Repositories

#### Arch Linux

To install from AUR (maintained by @vestingz):

```sh
...install cfv...
```
~~~

**Comment by vestingz** [comment]
> If you plan to keep the AUR package up-to-date

I'll be happily doing that - git-packages automatically compile from the latest commit, so there is very little maintenance for me :smiley:

**Comment by lxp** [comment]
Thank you! I have slightly adapted the README.md after merging your pull request. If you find any mistake or want to improve the wording please leave a comment or just open another pull request :)

I hope I understood correctly, that the package follows the development branch (named `python3` here).
It might not be stable all the time, so do you think, you can also add our usual releases to AUR?

**Comment by vestingz** [comment]
> Thank you! I have slightly adapted the README.md after merging your pull request. If you find any mistake or want to improve the wording please leave a comment or just open another pull request :)

All good! 👍🏽

> I hope I understood correctly, that the package follows the development branch (named `python3` here). It might not be stable all the time, so do you think, you can also add our usual releases to AUR?

Yes, -git-packages follow the dev branch, that is correct, so AUR users have to [expect instabilities](https://wiki.archlinux.org/title/Arch_User_Repository#What_is_the_difference_between_foo_and_foo-git_packages?).

Unfortunately there is already a [package](https://aur.archlinux.org/packages/cfv) in the AUR which seems to follow stable releases, so for the time being I cannot create a duplicate of that. I already flagged it to be out of date on Nov 1st, so let's wait until the beginning of Dec before submitting an orphan request.

**Comment by lxp** [comment]
> Unfortunately there is already a [package](https://aur.archlinux.org/packages/cfv) in the AUR which seems to follow stable releases, so for the time being I cannot create a duplicate of that. I already flagged it to be out of date on Nov 1st, so let's wait until the beginning of Dec before submitting an orphan request.

I did not notice that you already took some action regarding the stable package, thank you! :+1:
I think you know the AUR specifics better, so I am fully leaving it to you, when and what to do.
