### ISSUE TITLE
Module 'TERMIOS' not found

### ISSUE THREAD

**Issue by vestingz** [cfv-project/cfv#48]
Instead, it should be renamed to 'termios' (like two lines above):

https://github.com/cfv-project/cfv/blob/1debfeb4cc91d97822b3222c52c4d64247280b94/lib/cfv/term.py#L13

**Comment by lxp** [comment]
This is only a fallback if 'termios' is not found. Do you have some problem with it or was it just reported by some tool?

I think the only thing we could do, would be to completely remove the fallback. However, I am not sure if this would break some systems.

**Comment by vestingz** [comment]
> This is only a fallback if 'termios' is not found. Do you have some problem with it or was it just reported by some tool?
> 
> I think the only thing we could do, would be to completely remove the fallback. However, I am not sure if this would break some systems.

Oh, ok, sorry for misreporting - may bad! Some Arch packaging tool reported this to be a potential issue, but I should have simply read the code more closely.
